### ISSUE TITLE
Constant FILTER_SANITIZE_STRING is deprecated

### ISSUE THREAD

**Issue by mstenz** [ip2location/ip2proxy-matomo#44]
Having thousands of this lines in my logs: 

> <html>
<body>

WARNING | IP2Proxy | 2023-10-20 00:01:41 UTC | 44 | /app/plugins/IP2Proxy/UserSettings.php(31): Deprecated - Constant FILTER_SANITIZE_STRING is deprecated - Matomo 4.15.1
-- | -- | -- | -- | --

</body>
</html>

and 

> /app/plugins/IP2Proxy/UserSettings.php(54): Deprecated - Creation of dynamic property Piwik\Plugins\IP2Proxy\UserSettings::$subscribedToEmailReport is deprecated - Matomo 4.15.1

**Comment by mstenz** [comment]
closed? how to fix?

**Comment by ip2location-com** [comment]
Please update to version 0.1.6 for the fix.

**Comment by mstenz** [comment]
thx
