### ISSUE TITLE
/plugins/IP2Proxy/UserSettings.php(51): Deprecated - Creation of dynamic property Piwik\Plugins\IP2Proxy\UserSettings::$subscribedToEmailReport is deprecated - Matomo 4.15.1

### ISSUE THREAD

**Issue by mstenz** [ip2location/ip2proxy-matomo#46]
Hi, there is again one new error with the new version: 

/app/plugins/IP2Proxy/UserSettings.php(51): Deprecated - Creation of dynamic property Piwik\Plugins\IP2Proxy\UserSettings::$subscribedToEmailReport is deprecated - Matomo 4.15.1

**Comment by ip2location-com** [comment]
It's a known issue for Matomo with PHP 8.2. This cannot be fixed within plugin level.

https://github.com/matomo-org/matomo/issues/20845
